# Curated 2026 offseason data per team (sources: NBA.com offseason deals, ESPN/CBS grades,
# BetMGM win totals via Yahoo, ESPN 2027 title odds, ESPN injury returns, NBA.com coaching tracker).
# Fetched 2026-09-22; roster moves updated 2026-09-26 (ESPN/NBA.com/AP: ATL↔CHA trade 9/23, MEM waives Russell 9/25, CHA hamstrings 9/25).

TITLE_ODDS = {
    "Oklahoma City Thunder": "+270", "San Antonio Spurs": "+270",
    "New York Knicks": "+900", "Philadelphia 76ers": "+900",
    "Boston Celtics": "+1300",
    "Cleveland Cavaliers": "+2500", "Detroit Pistons": "+2500", "Toronto Raptors": "+2500",
    "Minnesota Timberwolves": "+2500", "Denver Nuggets": "+2500",
    "Miami Heat": "+3000",
}

WIN_TOTAL = {  # BetMGM
    "Oklahoma City Thunder": 60.5, "San Antonio Spurs": 59.5, "New York Knicks": 52.5,
    "Boston Celtics": 51.5, "Detroit Pistons": 50.5, "Philadelphia 76ers": 50.5,
    "Denver Nuggets": 49.5, "Minnesota Timberwolves": 49.5, "Cleveland Cavaliers": 47.5,
    "Houston Rockets": 47.5, "Miami Heat": 46.5, "Los Angeles Lakers": 45.5,
    "Toronto Raptors": 45.5, "Indiana Pacers": 44.5, "Atlanta Hawks": 43.5,
    "Orlando Magic": 43.5, "Portland Trail Blazers": 43.5, "Golden State Warriors": 40.5,
    "Phoenix Suns": 38.5, "Charlotte Hornets": 37.5, "Utah Jazz": 35.5,
    "Washington Wizards": 35.5, "Dallas Mavericks": 34.5, "New Orleans Pelicans": 29.5,
    "LA Clippers": 28.5, "Memphis Grizzlies": 28.5, "Chicago Bulls": 27.5,
    "Milwaukee Bucks": 26.5, "Brooklyn Nets": 22.5, "Sacramento Kings": 21.5,
}

NEW_COACH = {
    "Milwaukee Bucks": "Taylor Jenkins（接替 Doc Rivers）",
    "Portland Trail Blazers": "Micah Nori（接替 Chauncey Billups）",
    "Dallas Mavericks": "Dusty May（自 Michigan 轉任）",
    "Chicago Bulls": "Tiago Splitter",
    "New Orleans Pelicans": "Jamahl Mosley",
    "Orlando Magic": "Sean Sweeney",
}

CONF = {
    "East": ["Atlanta Hawks", "Boston Celtics", "Brooklyn Nets", "Charlotte Hornets", "Chicago Bulls",
             "Cleveland Cavaliers", "Detroit Pistons", "Indiana Pacers", "Miami Heat", "Milwaukee Bucks",
             "New York Knicks", "Orlando Magic", "Philadelphia 76ers", "Toronto Raptors", "Washington Wizards"],
    "West": ["Dallas Mavericks", "Denver Nuggets", "Golden State Warriors", "Houston Rockets", "LA Clippers",
             "Los Angeles Lakers", "Memphis Grizzlies", "Minnesota Timberwolves", "New Orleans Pelicans",
             "Oklahoma City Thunder", "Phoenix Suns", "Portland Trail Blazers", "Sacramento Kings",
             "San Antonio Spurs", "Utah Jazz"],
}

# grade: (ESPN, CBS)  adds / departs: key names  injury: notes  outlook: zh summary  ats_angle: betting-model angle
TEAMS = {
    "Atlanta Hawks": dict(grade=("A-", "B-"),
        adds="Lu Dort、Aaron Wiggins（自 OKC 薪資傾倒）、Devin Carter、Dorian Finney-Smith（9/23 自 CHA 交易）；續約 CJ McCollum",
        departs="Zaccharie Risacher、Jonathan Kuminga、Buddy Hield、Ryan Nembhard（9/23 交易至 CHA）",
        injury="新秀替補中鋒 Henri Veesaar ACL 撕裂（9/22），賽季報銷；補進 Finney-Smith 補前場深度",
        outlook="沒付出首輪籤就補進兩名 OKC 冠軍輪替側翼，防守深度大幅升級；Trae Young 已於上季被傾倒至 WAS，球隊改以 Jalen Johnson + 側翼防守為主軸，Nickeil Alexander-Walker 續進步。",
        ats_angle="防守型補強通常在球季前段被市場低估，10–12 月主場受讓盤值得觀察。"),
    "Boston Celtics": dict(grade=("C-", "C-"),
        adds="Paul George（Brown 交易）、Mitchell Robinson（3 年 $47.4M）、Mike Conley",
        departs="Jaylen Brown（交易至 PHI）、Nikola Vučević",
        injury="",
        outlook="震撼交易送走 Brown 換來 34 歲的 George，兩家媒體都給 C-；仍有 Tatum 與 Robinson 補強籃板，但缺乏持球突破與換防能量。勝場盤 51.5 偏高。",
        ats_angle="市場仍以「豪門」定價，冠軍賠率 13-1；若 George 健康狀況反覆，客場讓分容易開太深，客場受讓方有機會。"),
    "Brooklyn Nets": dict(grade=("B-", None),
        adds="Julius Randle（4 隊交易）、Moritz Wagner、Day'Ron Sharpe、Keon Ellis；#6 Mikel Brown Jr.",
        departs="Nic Claxton",
        injury="",
        outlook="上季 20 勝球隊補進 Randle，但沒有長期方向；勝場盤 22.5 是聯盟倒數第二。",
        ats_angle="爛隊受讓早季常過盤（市場低估 Randle 的常規賽產出），但 3 月後擺爛風險高，需配合模型的時間抑制。"),
    "Charlotte Hornets": dict(grade=("A-", "A"),
        adds="Naz Reid、Dennis Schröder、Grayson Allen、Royce O'Neale、Buddy Hield、Ryan Nembhard（9/23 自 ATL 交易）；#14 Hannes Steinbach；續約 Coby White",
        departs="LaMelo Ball（交易至 MIN）、Miles Bridges、Dorian Finney-Smith（9/23 交易至 ATL）",
        injury="Kon Knueppel 左腿後肌、Grant Williams 右腿後肌（9/25 公布）：缺席全部季前賽，開季首週再評估，10/21 開幕戰成疑",
        outlook="賣掉 LaMelo 換來大量未來籤，帳面上「資產管理 A」但即戰力下降；老將補強讓底線不至於崩盤。勝場盤 37.5。",
        ats_angle="老將多、上限低的球隊常是「輸球但過盤」型，主場受讓值得追蹤；前端 mcw 指標應偏低。"),
    "Chicago Bulls": dict(grade=("C+", "C"),
        adds="Nic Claxton、Norman Powell、#4 Caleb Wilson；續約 Zach Collins",
        departs="Collin Sexton、Anfernee Simons、Nick Richards",
        injury="",
        outlook="新教練 Tiago Splitter，用薪資空間補了中鋒與射手，但 Powell 當第一得分手代表天花板有限。上季失分 121.5，防守是硬傷。",
        ats_angle="防守爛隊在大分盤更有價值；讓分方面早季客場不宜跟。"),
    "Cleveland Cavaliers": dict(grade=("C", "D"),
        adds="Peyton Watson（5 隊 sign-and-trade）、Mario Hezonja、Khalifa Diop；Mitchell 4 年續約、Harden 3 年續約",
        departs="Dean Wade、Dennis Schröder、Max Strus、Larry Nance Jr.、Georges Niang",
        injury="",
        outlook="等 LeBron 等到空，防守深度反而流失；東決被橫掃後沒有明確補強，士氣與季中交易風險並存。勝場盤 47.5。",
        ats_angle="上季 CLE 常規賽強、季後賽弱；早季主場讓分仍可跟，但 2 月後若傳出交易傳聞，模型信號需降權。"),
    "Dallas Mavericks": dict(grade=("B-", "C"),
        adds="Zaccharie Risacher、Santi Aldama、Marcus Sasser、#? Morez Johnson Jr.、Dwight Powell（9/25 回歸）；新教練 Dusty May",
        departs="Klay Thompson、Khris Middleton、Ryan Nembhard、Marvin Bagley III",
        injury="Kyrie Irving ACL 康復 19 個月，訓練營可上；可能成為交易截止日籌碼。Dereck Lively II 腳部手術後尚未通過醫療許可（9/25）",
        outlook="圍繞 Cooper Flagg 囤積前鋒，後場只剩 Kyrie 撐；新教練體系需要磨合期。勝場盤 34.5 明顯低於部分模型（37.5）。",
        ats_angle="Flagg 第二年的成長是市場最可能低估的變數；11 月後若 Kyrie 健康，主場受讓有價值。"),
    "Denver Nuggets": dict(grade=("C", None),
        adds="DeMar DeRozan（1 年）、Marvin Bagley III；續約 Tyus Jones",
        departs="Peyton Watson、Tim Hardaway Jr.、Jonas Valanciunas",
        injury="",
        outlook="幾乎沒動，Jokić 仍是聯盟最穩的地板；但 MPJ 交易後遺症與防守（季後賽 6 場 5 場失 110+）沒解決。勝場盤 49.5。",
        ats_angle="DEN 主場（高海拔）ATS 長期正期望；客場背靠背是模型歷來的負 EV 區，維持過濾。"),
    "Detroit Pistons": dict(grade=("C-", "C+"),
        adds="John Collins、Isaiah Joe、Gary Harris、Taurean Prince；Ausar Thompson 5 年續約、Huerter 續約",
        departs="Isaiah Stewart、Tobias Harris、Caris LeVert",
        injury="",
        outlook="東區第一防守效率仍在，但沒找到 Cade 身邊的第二持球者；換掉三名老將換成三名角色球員，屬於平移。勝場盤 50.5，冠軍賠率 25-1。",
        ats_angle="防守型球隊過盤穩定，尤其主場對弱隊時「贏且過盤」機率高；上季 DET 主場 ATS 是東區前段，延續性高。"),
    "Golden State Warriors": dict(grade=("C+", "C-"),
        adds="Al Horford、Porziņģis、De'Anthony Melton 續約；Georges Niang；#? Yaxel Lendeborg",
        departs="Quinten Post",
        injury="Jimmy Butler 右膝 ACL，最樂觀 1–2 月回歸；訓練營僅個人訓練",
        outlook="LeBron 沒來、Butler 缺席半季，Curry 冠軍窗口實質關閉；勝場盤 40.5 但多數模型看 under。",
        ats_angle="沒有 Butler 的 GSW 是典型「名氣 > 實力」隊，客場讓分容易開高 → 客場受讓對手值得看。"),
    "Houston Rockets": dict(grade=("B+", "C+"),
        adds="Marcus Smart、Bogdan Bogdanović；Tari Eason 5 年續約、Amen Thompson 5 年續約",
        departs="Dorian Finney-Smith、Josh Okogie",
        injury="Fred VanVleet 10 月可全時上場；Steven Adams 腳踝手術後預計開季可上",
        outlook="防守再升級，VanVleet 回歸解決組織問題；賭的是老將健康。勝場盤 47.5。",
        ats_angle="HOU 二次進攻聯盟第一，主場對小球隊的讓分穩；模型上季對 HOU 主場信號命中率高。"),
    "Indiana Pacers": dict(grade=("B-", "C"),
        adds="Kelly Oubre Jr.、Larry Nance Jr.",
        departs="第 5 順位籤（交易）",
        injury="Tyrese Haliburton 阿基里斯腱康復，開季可上，早季可能限制上場時間",
        outlook="Haliburton 回歸是東區最大變數，但團隊補強保守；勝場盤 44.5 反映市場對阿基里斯腱回歸的保守。",
        ats_angle="早季 Haliburton 限時 → 前 20 場的 IND 實力被高估，客場讓分不跟；1 月後重新評估。"),
    "LA Clippers": dict(grade=("Incomplete", "A-"),
        adds="Brandon Ingram、Gradey Dick（Kawhi 交易）、Max Strus、Rui Hachimura、Johni Broome；#5 Keaton Wagler；續約 Beal",
        departs="Kawhi Leonard（9/14 交易至 TOR 正式完成；Aspiration 案結案：罰款 $30M、沒收 2029–33 五個首輪籤、Ballmer 禁賽一年、Frank 禁賽半年）、John Collins、Bogdanović、Mathurin",
        injury="",
        outlook="正式進入重建，勝場盤 28.5；Ingram + Garland + Beal 是「有名字沒勝場」的組合。",
        ats_angle="重建隊早季偶爾爆冷，但 12 月後多半崩盤；模型的 mcw 對 LAC 應偏低，客場信號降權。注意：2029–33 首輪籤全數沒收，LAC 沒有擺爛誘因，下半季不宜套用「重建隊尾盤崩盤」假設。"),
    "Los Angeles Lakers": dict(grade=("C+", None),
        adds="Walker Kessler（sign-and-trade，4 年 $130M）、Quentin Grimes、Collin Sexton、Matisse Thybulle、Kevon Looney、Mamukelashvili；Reaves 4 年續約",
        departs="LeBron James（PHI）、Deandre Ayton、Rui Hachimura、Marcus Smart、Jaxson Hayes、Luke Kennard",
        injury="Luka Dončić 二級腿後肌拉傷已痊癒；Kessler 肩膀唇盂撕裂已痊癒",
        outlook="後 LeBron 時代由 Luka + Reaves 主導，補進 Kessler 補籃板，但前鋒群薄弱、選秀資產耗盡。勝場盤 45.5。",
        ats_angle="Luka 主導的球隊上季得分王但季後賽失利；市場對 LAL 的「豪門溢價」仍在，客場讓分方 LAL 是歷來負 EV 之一，維持過濾。"),
    "Memphis Grizzlies": dict(grade=("B", "B-"),
        adds="#3 Cameron Boozer、Isaiah Stewart、Jerami Grant、Quinten Post、Kris Murray",
        departs="Ja Morant（交易至 POR）、Santi Aldama、KCP（買斷）、D'Angelo Russell（9/25 裁掉，19 人名單需砍至 15）",
        injury="Zach Edey 左腳踝 9 個月內第二次手術，預計開季可上",
        outlook="送走 Morant 換來 Boozer + 前場深度，走年輕化路線；勝場盤 28.5 屬於「準擺爛」定價。",
        ats_angle="年輕重建隊主場對強隊受讓大分時常過盤（垃圾時間）；模型 garbage-time 過濾需開啟。"),
    "Miami Heat": dict(grade=("B", "B-"),
        adds="Giannis Antetokounmpo（交易，6/22）、Klay Thompson、Bobby Portis、Tim Hardaway Jr.、Nick Richards；#13 Nate Ament；Wiggins 續約",
        departs="Tyler Herro、Jaime Jaquez Jr.、Kel'el Ware、Jakučionis（全部給 MIL）、Norman Powell",
        injury="",
        outlook="用「幾乎所有東西」換 Giannis，Giannis + Bam 的防守是聯盟頂級，但外線與持球創造不足。勝場盤 46.5，冠軍 30-1。",
        ats_angle="Giannis 球隊常規賽輾壓弱隊、季後賽被防守針對；早季主場讓分對弱隊可跟，季後賽降權。"),
    "Milwaukee Bucks": dict(grade=("B", "C-"),
        adds="Tyler Herro、Jaime Jaquez Jr.、Kel'el Ware、Jakučionis、Caris LeVert；Gary Trent Jr. 4 年續約；新教練 Taylor Jenkins",
        departs="Giannis Antetokounmpo、Bobby Portis、Gary Harris、Taurean Prince",
        injury="",
        outlook="失去 Giannis 後沒有核心，勝場盤 26.5；Herro 當第一得分手加上 Kuzma / Turner 老化，市場預期崩盤。",
        ats_angle="Giannis 效應消失後市場可能仍慣性給 MIL 太多分；早季 MIL 客場受讓對手（讓分方）值得看。"),
    "Minnesota Timberwolves": dict(grade=("C+", "B"),
        adds="LaMelo Ball（4 隊交易）、Jonathan Kuminga、Cody Williams、Trey Lyles；Dosunmu 續約",
        departs="Julius Randle、Naz Reid、Mike Conley、Kyle Anderson",
        injury="",
        outlook="把前場深度全換成 LaMelo 的持球投籃，Gobert 仍鎮守禁區；押注後場但前鋒深度極薄。勝場盤 49.5，冠軍 25-1。",
        ats_angle="LaMelo 的健康是最大變數；MIN 主場 ATS 歷來偏正，但客場背靠背出現 LaMelo 缺陣時模型需即時抓傷兵。"),
    "New Orleans Pelicans": dict(grade=("D", None),
        adds="Bennedict Mathurin、AJ Johnson、Trendon Watford；續約 DeAndre Jordan、Saddiq Bey；新教練 Jamahl Mosley",
        departs="Jordan Hawkins、Micah Peavy、Kevon Looney",
        injury="Dejounte Murray 阿基里斯腱斷裂已康復，訓練營可上",
        outlook="26-56 後幾乎沒動，Zion / Murray 交易傳聞不斷，勝場盤 29.5 屬擺爛定價。",
        ats_angle="擺爛隊 3 月後 ATS 極差，模型時間抑制必須維持；早季主場受讓仍有零星價值。"),
    "New York Knicks": dict(grade=("B-", "C+"),
        adds="Andre Drummond、Landry Shamet 續約、Jose Alvarado 續約、Jordan Clarkson 續約",
        departs="Mitchell Robinson（BOS）、Jeremy Sochan、Ariel Hukporti",
        injury="",
        outlook="衛冕軍核心完整，但用 Drummond 換 Robinson 是實質降級；留在第二豪華稅線下保有彈性。勝場盤 52.5（東區最高）、冠軍 +900。",
        ats_angle="上季 NYK 總決賽客場 5-0 ATS；衛冕軍常規賽常「贏球不過盤」，主場讓分大於 8 分時需謹慎。"),
    "Oklahoma City Thunder": dict(grade=("C+", "C+"),
        adds="Isaiah Hartenstein 3 年續約、Kenrich Williams 續約、大量二輪籤",
        departs="Lu Dort、Aaron Wiggins（ATL）、Isaiah Joe（DET）",
        injury="Jalen Williams 腿後肌反覆，夏季調整身體，預計開季可上",
        outlook="為脫離第二豪華稅線送走三名輪替，深度下降但核心 SGA / JDub / Chet 完整；西決敗給 SAS 後仍是共同冠軍熱門（+270）。勝場盤 60.5 聯盟最高。",
        ats_angle="OKC 2024 年起主場 86-17；主場讓分即使 10+ 分過盤率仍高，是模型 home≥8% 信號的主要來源之一。"),
    "Orlando Magic": dict(grade=("D+", "C-"),
        adds="Nikola Vučević（底薪回歸）；續約 Isaac、Jevon Carter；新教練 Sean Sweeney",
        departs="Moritz Wagner",
        injury="",
        outlook="躲過第二豪華稅線但沒解決進攻問題（上季進攻效率第 21），換教練是唯一變數。勝場盤 43.5。",
        ats_angle="防守強、進攻差的球隊小分盤有價值；讓分方面主場對弱隊過盤率尚可，客場不跟。"),
    "Philadelphia 76ers": dict(grade=("A-", "A+"),
        adds="LeBron James（2 年）、Jaylen Brown（交易）、Dean Wade、Anfernee Simons、KCP、Hukporti",
        departs="Paul George、兩個首輪籤、Grimes、Oubre、Drummond、Broome",
        injury="Joel Embiid 膝蓋 / 斜腹肌，預計開季可上但缺賽史悠久；Adem Bona 左腳扭傷（FIBA）",
        outlook="用 George + 兩首輪 + MLE 換來 LeBron + Brown，是休賽季最大贏家；Maxey / Embiid / Brown / LeBron 是東區最深陣容。冠軍賠率從 60-1 飆到 +900，勝場盤 50.5。",
        ats_angle="市場已反映到 +900，早季讓分會開得深；Embiid 缺陣場次的盤口修正是主要價值來源，傷兵即時更新最重要。"),
    "Phoenix Suns": dict(grade=("B-", None),
        adds="Miles Bridges（交易，付出 2033 無保護首輪）、Luke Kennard、Collin Gillespie 續約、Mark Williams 續約；Dillon Brooks 3 年延長",
        departs="Grayson Allen、Royce O'Neale",
        injury="",
        outlook="深度補強不錯，但為一年 Bridges 付出 2033 無保護籤；Brooks / Green / Bridges 天花板有限。勝場盤 38.5。",
        ats_angle="中段球隊最難預測，模型 edge 通常不足門檻；不強求。"),
    "Portland Trail Blazers": dict(grade=("B-", None),
        adds="Ja Morant（交易）、Jeremy Sochan、Robert Williams III 續約；新教練 Micah Nori",
        departs="Jerami Grant、Kris Murray、Matisse Thybulle",
        injury="Ja Morant 左肘 UCL，訓練營狀態未定；Damian Lillard 阿基里斯腱康復，36 歲開季可上",
        outlook="Morant + Lillard + Avdija + Clingan，四名後衛的兼容性是問題；新教練體系。勝場盤 43.5。",
        ats_angle="Morant 早季可能缺陣 → 前 15 場盤口會混亂，模型應等傷兵穩定後再跟；Avdija 進步是 under-the-radar 變數。"),
    "Sacramento Kings": dict(grade=("C", None),
        adds="Ben Simmons（1 年）、#7 Darius Acuff Jr.；續約 Achiuwa",
        departs="DeMar DeRozan（DEN）、Devin Carter",
        injury="Domantas Sabonis 左膝半月板部分撕裂，預計開季可上",
        outlook="裁掉 DeRozan、清空薪資，勝場盤 21.5 是聯盟最低，2011 年以來最低預期。",
        ats_angle="全季擺爛隊：早季受讓偶有價值，1 月後 ATS 崩盤；模型應把 SAC 相關信號的 mcw 上限鎖低。"),
    "San Antonio Spurs": dict(grade=("A", "B"),
        adds="Tobias Harris、Jayden Quaintance（選秀）；Wembanyama 5 年 $251M 續約（放棄 Rose Rule 加成）、Barnes / Champagnie 續約",
        departs="無重大流失",
        injury="",
        outlook="總決賽亞軍陣容完整回歸，Wemby 續約省下 $50M+ 彈性；勝場盤 59.5 是隊史 30 年最高，冠軍共同熱門 +270。",
        ats_angle="上季總決賽 SAS 主場 0-3 ATS（讓分開太深）；常規賽 SAS 主場讓分過盤率高，但季後賽主場需降權。"),
    "Toronto Raptors": dict(grade=("Incomplete", "B-"),
        adds="Kawhi Leonard（交易 9/14 正式完成）、Kyle Anderson",
        departs="Brandon Ingram、Gradey Dick、Mamukelashvili",
        injury="Kawhi Leonard 歷年出賽率低；交易已於 9/14 完成，不再有交易變數",
        outlook="若 Kawhi 健康，有機會爭東區；但板凳因交易變薄。勝場盤 45.5，冠軍 25-1。",
        ats_angle="Kawhi 輪休場次是最大 ATS 變數；模型需在盤口出現異常移動（≥2 分）時優先標記。"),
    "Utah Jazz": dict(grade=("A", "B+"),
        adds="#2 Darryn Peterson、Josh Green、Jaxson Hayes、Josh Okogie；Keyonte George 5 年續約、Nurkić 續約",
        departs="Walker Kessler（sign-and-trade 換兩張無保護首輪）、Cody Williams",
        injury="Jaren Jackson Jr. 左膝增生，預計開季可上（DPOY 候選，補 Kessler 空缺）",
        outlook="Kessler 換到的籤比 Kawhi 還多，資產管理滿分；即戰力靠 JJJ + Peterson，勝場盤 35.5。",
        ats_angle="年輕上升隊在主場受讓時歷來正期望；Peterson 若早段就爆發，市場調整慢。"),
    "Washington Wizards": dict(grade=("D+", "C-"),
        adds="#1 AJ Dybantsa、Deandre Ayton（交易）、Khris Middleton、Tre Mann；Trae Young 4 年續約",
        departs="D'Angelo Russell、Jaden Hardy、Cam Whitmore",
        injury="Trae Young 右腿 MCL / 股四頭肌已痊癒；Anthony Davis 手傷已可訓練",
        outlook="給 Trae Young 四年頂薪被兩家媒體批評（ATL 曾為避免一年 option 把他傾倒），Ayton + AD 前場重疊；但 Dybantsa + Sarr 讓底線抬高。勝場盤 35.5。",
        ats_angle="從 26 勝隊變 35 勝隊的球隊，早季受讓盤價值最高（市場定價落後）；是模型 away≥9% 信號可能出現的來源。"),
}
